"""3rd

Revision ID: 104c384ec2ce
Revises: 33cad7a25b62
Create Date: 2024-05-07 11:01:17.132021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104c384ec2ce'
down_revision = '33cad7a25b62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
