"""this no life

Revision ID: ec51e44493e9
Revises: f21f95066957
Create Date: 2024-05-19 02:46:29.542648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec51e44493e9'
down_revision = 'f21f95066957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('from_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'from_phone')
    # ### end Alembic commands ###
